// Generated by https://quicktype.io

export interface Prueba {
  id:          string;
  firstname:   string;
  email:       string;
  password:    string;
  profile:     Profile;
  role:        Role;
  appointment: Appointment[];
}

export interface Appointment {
  id:     number;
  date:   string;
  hour:   string;
  status: string;
}

export interface Profile {
  createdAt: string;
  updatedAt: string;
  id:        number;
  lastname:  null;
  idCard:    null;
  phone:     null;
}

export interface Role {
  id:   number;
  name: string;
}



// export interface Prueba {
//   id?:        string|null;
//   firstname?: string|null;
//   email?:     string|null;
//   password?:  string|null;
//   profile?:   Profile|null;
//   role?:      Role|null;
//   token?:     string|null;
// }

// export interface Profile {
//   createdAt: string;
//   updatedAt: string;
//   id:        number;
//   lastname:  null;
//   idCard:    null;
//   phone:     null;
// }

// export interface Role {
//   id:   number;
//   name: string;
// }
